channels:
  # Define conda channels here. 
  - defaults
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.7.5
  - tesseract
  - pip=20.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==7.4.2 # https://rpaframework.org/releasenotes.html
    - rpaframework-recognition==0.6.0
